import { Link } from "react-router-dom"
import { FaCompactDisc } from "react-icons/fa";
import { MdLibraryMusic, MdOutlineLineWeight, MdVideoLibrary } from "react-icons/md";
import { BsBarChartFill } from "react-icons/bs";
import { FaRadio, FaHeart, FaHeadphonesSimple, FaPeopleGroup } from "react-icons/fa6";
import { IoAlbums } from "react-icons/io5";
import { useContext } from "react";
import { Cntx } from "../../context/DataContext";

function Main() {
    const { openAside, setOpenAside } = useContext(Cntx);

    return (
        <main className="bg-gray-900 relative w-full text-white">
            <aside className={`${openAside ? 'hidden' : 'block'} w-[290px] fixed left-0 top-[65px] h-screen overflow-y-auto pb-[100px] px-10 py-5 dark:bg-gray-950 dark:text-gray-800 z-50`}>
                <nav className="space-y-8 text-sm">
                    <div class="muzieknootjes">
                        <div class="noot-1">&#9835; &#9833;</div>
                        <div class="noot-2">&#9833;</div>
                        <div class="noot-3">&#9839; &#9834;</div>
                        <div class="noot-4">&#9834;</div>
                    </div>
                    <div className="space-y-3">
                        <h2 className="text-sm font-semibold tracking-widest mb-5 dark:text-gray-600">
                            Browse
                        </h2>
                        <div className="flex flex-col space-y-1">
                            <Link className="text-gray-300 p-2.5 font-semibold flex items-center gap-4 hover:text-blue-300 transition-all rounded-md hover:bg-[#d4dce418]"><FaCompactDisc className="text-lg" />Discover</Link>
                            <Link className="text-gray-300 p-2.5 font-semibold flex items-center gap-4 hover:text-blue-300 transition-all rounded-md hover:bg-[#d4dce418]"><MdLibraryMusic className="text-lg" />Browse</Link>
                            <Link className="text-gray-300 p-2.5 font-semibold flex items-center gap-4 hover:text-blue-300 transition-all rounded-md hover:bg-[#d4dce418]"><MdOutlineLineWeight className="text-lg" />New Release</Link>
                            <Link className="text-gray-300 p-2.5 font-semibold flex items-center gap-4 hover:text-blue-300 transition-all rounded-md hover:bg-[#d4dce418]"><BsBarChartFill className="text-lg" />Charts</Link>
                            <Link className="text-gray-300 p-2.5 font-semibold flex items-center gap-4 hover:text-blue-300 transition-all rounded-md hover:bg-[#d4dce418]"><FaRadio className="text-lg" />Radio</Link>
                        </div>
                    </div> <br />
                    <div class="muzieknootjes">
                        <div class="noot-1">&#9835; &#9833;</div>
                        <div class="noot-2">&#9833;</div>
                        <div class="noot-3">&#9839; &#9834;</div>
                        <div class="noot-4">&#9834;</div>
                    </div>
                    <div className="space-y-3">
                        <h2 className="text-sm font-semibold tracking-widest mb-5 dark:text-gray-600">
                            Library
                        </h2>
                        <div className="flex flex-col space-y-1">
                            <Link className="text-gray-300 p-2.5 font-semibold flex items-center gap-4 hover:text-blue-300 transition-all rounded-md hover:bg-[#d4dce418]"><MdVideoLibrary className="text-lg" />Playlist</Link>
                            <Link className="text-gray-300 p-2.5 font-semibold flex items-center gap-4 hover:text-blue-300 transition-all rounded-md hover:bg-[#d4dce418]"><FaHeadphonesSimple className="text-lg" />Stream</Link>
                            <Link className="text-gray-300 p-2.5 font-semibold flex items-center gap-4 hover:text-blue-300 transition-all rounded-md hover:bg-[#d4dce418]"><FaHeart className="text-lg" />Likes</Link>
                            <Link className="text-gray-300 p-2.5 font-semibold flex items-center gap-4 hover:text-blue-300 transition-all rounded-md hover:bg-[#d4dce418]"><IoAlbums className="text-lg" />Albums</Link>
                            <Link className="text-gray-300 p-2.5 font-semibold flex items-center gap-4 hover:text-blue-300 transition-all rounded-md hover:bg-[#d4dce418]"><FaPeopleGroup className="text-lg" />Artist</Link>
                        </div>
                    </div>
                    <ul className="text-gray-700">
                        <li>The soundtrack to your soul begins here.</li> <br />
                        <li>2024 © Mimi & Aysu</li> 
                    </ul>
                </nav>
            </aside>
            <div className="ml-[25%] py-[10%]">
                <h1>Main Content</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque numquam nam expedita excepturi? Earum sunt impedit labore expedita esse dolorem perferendis nobis, doloribus optio dolores odit sed autem culpa nisi assumenda corrupti officia debitis aperiam reprehenderit ipsa corporis. Inventore, tenetur minus voluptatum eaque saepe at quas, nulla voluptatem earum illum voluptatibus excepturi, vero accusamus. Magnam dolore, ex inventore officiis, nemo soluta doloremque asperiores nesciunt praesentium nobis nisi quam dicta blanditiis necessitatibus repudiandae modi laudantium, aut quas corporis repellat ratione perferendis? Quasi molestias rerum eligendi rem, deserunt, dignissimos perspiciatis aut laborum dolore maiores id corrupti quia doloremque maxime! Et, quis repellat?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque numquam nam expedita excepturi? Earum sunt impedit labore expedita esse dolorem perferendis nobis, doloribus optio dolores odit sed autem culpa nisi assumenda corrupti officia debitis aperiam reprehenderit ipsa corporis. Inventore, tenetur minus voluptatum eaque saepe at quas, nulla voluptatem earum illum voluptatibus excepturi, vero accusamus. Magnam dolore, ex inventore officiis, nemo soluta doloremque asperiores nesciunt praesentium nobis nisi quam dicta blanditiis necessitatibus repudiandae modi laudantium, aut quas corporis repellat ratione perferendis? Quasi molestias rerum eligendi rem, deserunt, dignissimos perspiciatis aut laborum dolore maiores id corrupti quia doloremque maxime! Et, quis repellat?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque numquam nam expedita excepturi? Earum sunt impedit labore expedita esse dolorem perferendis nobis, doloribus optio dolores odit sed autem culpa nisi assumenda corrupti officia debitis aperiam reprehenderit ipsa corporis. Inventore, tenetur minus voluptatum eaque saepe at quas, nulla voluptatem earum illum voluptatibus excepturi, vero accusamus. Magnam dolore, ex inventore officiis, nemo soluta doloremque asperiores nesciunt praesentium nobis nisi quam dicta blanditiis necessitatibus repudiandae modi laudantium, aut quas corporis repellat ratione perferendis? Quasi molestias rerum eligendi rem, deserunt, dignissimos perspiciatis aut laborum dolore maiores id corrupti quia doloremque maxime! Et, quis repellat?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque numquam nam expedita excepturi? Earum sunt impedit labore expedita esse dolorem perferendis nobis, doloribus optio dolores odit sed autem culpa nisi assumenda corrupti officia debitis aperiam reprehenderit ipsa corporis. Inventore, tenetur minus voluptatum eaque saepe at quas, nulla voluptatem earum illum voluptatibus excepturi, vero accusamus. Magnam dolore, ex inventore officiis, nemo soluta doloremque asperiores nesciunt praesentium nobis nisi quam dicta blanditiis necessitatibus repudiandae modi laudantium, aut quas corporis repellat ratione perferendis? Quasi molestias rerum eligendi rem, deserunt, dignissimos perspiciatis aut laborum dolore maiores id corrupti quia doloremque maxime! Et, quis repellat?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque numquam nam expedita excepturi? Earum sunt impedit labore expedita esse dolorem perferendis nobis, doloribus optio dolores odit sed autem culpa nisi assumenda corrupti officia debitis aperiam reprehenderit ipsa corporis. Inventore, tenetur minus voluptatum eaque saepe at quas, nulla voluptatem earum illum voluptatibus excepturi, vero accusamus. Magnam dolore, ex inventore officiis, nemo soluta doloremque asperiores nesciunt praesentium nobis nisi quam dicta blanditiis necessitatibus repudiandae modi laudantium, aut quas corporis repellat ratione perferendis? Quasi molestias rerum eligendi rem, deserunt, dignissimos perspiciatis aut laborum dolore maiores id corrupti quia doloremque maxime! Et, quis repellat?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque numquam nam expedita excepturi? Earum sunt impedit labore expedita esse dolorem perferendis nobis, doloribus optio dolores odit sed autem culpa nisi assumenda corrupti officia debitis aperiam reprehenderit ipsa corporis. Inventore, tenetur minus voluptatum eaque saepe at quas, nulla voluptatem earum illum voluptatibus excepturi, vero accusamus. Magnam dolore, ex inventore officiis, nemo soluta doloremque asperiores nesciunt praesentium nobis nisi quam dicta blanditiis necessitatibus repudiandae modi laudantium, aut quas corporis repellat ratione perferendis? Quasi molestias rerum eligendi rem, deserunt, dignissimos perspiciatis aut laborum dolore maiores id corrupti quia doloremque maxime! Et, quis repellat?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque numquam nam expedita excepturi? Earum sunt impedit labore expedita esse dolorem perferendis nobis, doloribus optio dolores odit sed autem culpa nisi assumenda corrupti officia debitis aperiam reprehenderit ipsa corporis. Inventore, tenetur minus voluptatum eaque saepe at quas, nulla voluptatem earum illum voluptatibus excepturi, vero accusamus. Magnam dolore, ex inventore officiis, nemo soluta doloremque asperiores nesciunt praesentium nobis nisi quam dicta blanditiis necessitatibus repudiandae modi laudantium, aut quas corporis repellat ratione perferendis? Quasi molestias rerum eligendi rem, deserunt, dignissimos perspiciatis aut laborum dolore maiores id corrupti quia doloremque maxime! Et, quis repellat?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque numquam nam expedita excepturi? Earum sunt impedit labore expedita esse dolorem perferendis nobis, doloribus optio dolores odit sed autem culpa nisi assumenda corrupti officia debitis aperiam reprehenderit ipsa corporis. Inventore, tenetur minus voluptatum eaque saepe at quas, nulla voluptatem earum illum voluptatibus excepturi, vero accusamus. Magnam dolore, ex inventore officiis, nemo soluta doloremque asperiores nesciunt praesentium nobis nisi quam dicta blanditiis necessitatibus repudiandae modi laudantium, aut quas corporis repellat ratione perferendis? Quasi molestias rerum eligendi rem, deserunt, dignissimos perspiciatis aut laborum dolore maiores id corrupti quia doloremque maxime! Et, quis repellat?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque numquam nam expedita excepturi? Earum sunt impedit labore expedita esse dolorem perferendis nobis, doloribus optio dolores odit sed autem culpa nisi assumenda corrupti officia debitis aperiam reprehenderit ipsa corporis. Inventore, tenetur minus voluptatum eaque saepe at quas, nulla voluptatem earum illum voluptatibus excepturi, vero accusamus. Magnam dolore, ex inventore officiis, nemo soluta doloremque asperiores nesciunt praesentium nobis nisi quam dicta blanditiis necessitatibus repudiandae modi laudantium, aut quas corporis repellat ratione perferendis? Quasi molestias rerum eligendi rem, deserunt, dignissimos perspiciatis aut laborum dolore maiores id corrupti quia doloremque maxime! Et, quis repellat?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque numquam nam expedita excepturi? Earum sunt impedit labore expedita esse dolorem perferendis nobis, doloribus optio dolores odit sed autem culpa nisi assumenda corrupti officia debitis aperiam reprehenderit ipsa corporis. Inventore, tenetur minus voluptatum eaque saepe at quas, nulla voluptatem earum illum voluptatibus excepturi, vero accusamus. Magnam dolore, ex inventore officiis, nemo soluta doloremque asperiores nesciunt praesentium nobis nisi quam dicta blanditiis necessitatibus repudiandae modi laudantium, aut quas corporis repellat ratione perferendis? Quasi molestias rerum eligendi rem, deserunt, dignissimos perspiciatis aut laborum dolore maiores id corrupti quia doloremque maxime! Et, quis repellat?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque numquam nam expedita excepturi? Earum sunt impedit labore expedita esse dolorem perferendis nobis, doloribus optio dolores odit sed autem culpa nisi assumenda corrupti officia debitis aperiam reprehenderit ipsa corporis. Inventore, tenetur minus voluptatum eaque saepe at quas, nulla voluptatem earum illum voluptatibus excepturi, vero accusamus. Magnam dolore, ex inventore officiis, nemo soluta doloremque asperiores nesciunt praesentium nobis nisi quam dicta blanditiis necessitatibus repudiandae modi laudantium, aut quas corporis repellat ratione perferendis? Quasi molestias rerum eligendi rem, deserunt, dignissimos perspiciatis aut laborum dolore maiores id corrupti quia doloremque maxime! Et, quis repellat?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque numquam nam expedita excepturi? Earum sunt impedit labore expedita esse dolorem perferendis nobis, doloribus optio dolores odit sed autem culpa nisi assumenda corrupti officia debitis aperiam reprehenderit ipsa corporis. Inventore, tenetur minus voluptatum eaque saepe at quas, nulla voluptatem earum illum voluptatibus excepturi, vero accusamus. Magnam dolore, ex inventore officiis, nemo soluta doloremque asperiores nesciunt praesentium nobis nisi quam dicta blanditiis necessitatibus repudiandae modi laudantium, aut quas corporis repellat ratione perferendis? Quasi molestias rerum eligendi rem, deserunt, dignissimos perspiciatis aut laborum dolore maiores id corrupti quia doloremque maxime! Et, quis repellat?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque numquam nam expedita excepturi? Earum sunt impedit labore expedita esse dolorem perferendis nobis, doloribus optio dolores odit sed autem culpa nisi assumenda corrupti officia debitis aperiam reprehenderit ipsa corporis. Inventore, tenetur minus voluptatum eaque saepe at quas, nulla voluptatem earum illum voluptatibus excepturi, vero accusamus. Magnam dolore, ex inventore officiis, nemo soluta doloremque asperiores nesciunt praesentium nobis nisi quam dicta blanditiis necessitatibus repudiandae modi laudantium, aut quas corporis repellat ratione perferendis? Quasi molestias rerum eligendi rem, deserunt, dignissimos perspiciatis aut laborum dolore maiores id corrupti quia doloremque maxime! Et, quis repellat?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque numquam nam expedita excepturi? Earum sunt impedit labore expedita esse dolorem perferendis nobis, doloribus optio dolores odit sed autem culpa nisi assumenda corrupti officia debitis aperiam reprehenderit ipsa corporis. Inventore, tenetur minus voluptatum eaque saepe at quas, nulla voluptatem earum illum voluptatibus excepturi, vero accusamus. Magnam dolore, ex inventore officiis, nemo soluta doloremque asperiores nesciunt praesentium nobis nisi quam dicta blanditiis necessitatibus repudiandae modi laudantium, aut quas corporis repellat ratione perferendis? Quasi molestias rerum eligendi rem, deserunt, dignissimos perspiciatis aut laborum dolore maiores id corrupti quia doloremque maxime! Et, quis repellat?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque numquam nam expedita excepturi? Earum sunt impedit labore expedita esse dolorem perferendis nobis, doloribus optio dolores odit sed autem culpa nisi assumenda corrupti officia debitis aperiam reprehenderit ipsa corporis. Inventore, tenetur minus voluptatum eaque saepe at quas, nulla voluptatem earum illum voluptatibus excepturi, vero accusamus. Magnam dolore, ex inventore officiis, nemo soluta doloremque asperiores nesciunt praesentium nobis nisi quam dicta blanditiis necessitatibus repudiandae modi laudantium, aut quas corporis repellat ratione perferendis? Quasi molestias rerum eligendi rem, deserunt, dignissimos perspiciatis aut laborum dolore maiores id corrupti quia doloremque maxime! Et, quis repellat?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque numquam nam expedita excepturi? Earum sunt impedit labore expedita esse dolorem perferendis nobis, doloribus optio dolores odit sed autem culpa nisi assumenda corrupti officia debitis aperiam reprehenderit ipsa corporis. Inventore, tenetur minus voluptatum eaque saepe at quas, nulla voluptatem earum illum voluptatibus excepturi, vero accusamus. Magnam dolore, ex inventore officiis, nemo soluta doloremque asperiores nesciunt praesentium nobis nisi quam dicta blanditiis necessitatibus repudiandae modi laudantium, aut quas corporis repellat ratione perferendis? Quasi molestias rerum eligendi rem, deserunt, dignissimos perspiciatis aut laborum dolore maiores id corrupti quia doloremque maxime! Et, quis repellat?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque numquam nam expedita excepturi? Earum sunt impedit labore expedita esse dolorem perferendis nobis, doloribus optio dolores odit sed autem culpa nisi assumenda corrupti officia debitis aperiam reprehenderit ipsa corporis. Inventore, tenetur minus voluptatum eaque saepe at quas, nulla voluptatem earum illum voluptatibus excepturi, vero accusamus. Magnam dolore, ex inventore officiis, nemo soluta doloremque asperiores nesciunt praesentium nobis nisi quam dicta blanditiis necessitatibus repudiandae modi laudantium, aut quas corporis repellat ratione perferendis? Quasi molestias rerum eligendi rem, deserunt, dignissimos perspiciatis aut laborum dolore maiores id corrupti quia doloremque maxime! Et, quis repellat?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque numquam nam expedita excepturi? Earum sunt impedit labore expedita esse dolorem perferendis nobis, doloribus optio dolores odit sed autem culpa nisi assumenda corrupti officia debitis aperiam reprehenderit ipsa corporis. Inventore, tenetur minus voluptatum eaque saepe at quas, nulla voluptatem earum illum voluptatibus excepturi, vero accusamus. Magnam dolore, ex inventore officiis, nemo soluta doloremque asperiores nesciunt praesentium nobis nisi quam dicta blanditiis necessitatibus repudiandae modi laudantium, aut quas corporis repellat ratione perferendis? Quasi molestias rerum eligendi rem, deserunt, dignissimos perspiciatis aut laborum dolore maiores id corrupti quia doloremque maxime! Et, quis repellat?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque numquam nam expedita excepturi? Earum sunt impedit labore expedita esse dolorem perferendis nobis, doloribus optio dolores odit sed autem culpa nisi assumenda corrupti officia debitis aperiam reprehenderit ipsa corporis. Inventore, tenetur minus voluptatum eaque saepe at quas, nulla voluptatem earum illum voluptatibus excepturi, vero accusamus. Magnam dolore, ex inventore officiis, nemo soluta doloremque asperiores nesciunt praesentium nobis nisi quam dicta blanditiis necessitatibus repudiandae modi laudantium, aut quas corporis repellat ratione perferendis? Quasi molestias rerum eligendi rem, deserunt, dignissimos perspiciatis aut laborum dolore maiores id corrupti quia doloremque maxime! Et, quis repellat?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque numquam nam expedita excepturi? Earum sunt impedit labore expedita esse dolorem perferendis nobis, doloribus optio dolores odit sed autem culpa nisi assumenda corrupti officia debitis aperiam reprehenderit ipsa corporis. Inventore, tenetur minus voluptatum eaque saepe at quas, nulla voluptatem earum illum voluptatibus excepturi, vero accusamus. Magnam dolore, ex inventore officiis, nemo soluta doloremque asperiores nesciunt praesentium nobis nisi quam dicta blanditiis necessitatibus repudiandae modi laudantium, aut quas corporis repellat ratione perferendis? Quasi molestias rerum eligendi rem, deserunt, dignissimos perspiciatis aut laborum dolore maiores id corrupti quia doloremque maxime! Et, quis repellat?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque numquam nam expedita excepturi? Earum sunt impedit labore expedita esse dolorem perferendis nobis, doloribus optio dolores odit sed autem culpa nisi assumenda corrupti officia debitis aperiam reprehenderit ipsa corporis. Inventore, tenetur minus voluptatum eaque saepe at quas, nulla voluptatem earum illum voluptatibus excepturi, vero accusamus. Magnam dolore, ex inventore officiis, nemo soluta doloremque asperiores nesciunt praesentium nobis nisi quam dicta blanditiis necessitatibus repudiandae modi laudantium, aut quas corporis repellat ratione perferendis? Quasi molestias rerum eligendi rem, deserunt, dignissimos perspiciatis aut laborum dolore maiores id corrupti quia doloremque maxime! Et, quis repellat?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque numquam nam expedita excepturi? Earum sunt impedit labore expedita esse dolorem perferendis nobis, doloribus optio dolores odit sed autem culpa nisi assumenda corrupti officia debitis aperiam reprehenderit ipsa corporis. Inventore, tenetur minus voluptatum eaque saepe at quas, nulla voluptatem earum illum voluptatibus excepturi, vero accusamus. Magnam dolore, ex inventore officiis, nemo soluta doloremque asperiores nesciunt praesentium nobis nisi quam dicta blanditiis necessitatibus repudiandae modi laudantium, aut quas corporis repellat ratione perferendis? Quasi molestias rerum eligendi rem, deserunt, dignissimos perspiciatis aut laborum dolore maiores id corrupti quia doloremque maxime! Et, quis repellat?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque numquam nam expedita excepturi? Earum sunt impedit labore expedita esse dolorem perferendis nobis, doloribus optio dolores odit sed autem culpa nisi assumenda corrupti officia debitis aperiam reprehenderit ipsa corporis. Inventore, tenetur minus voluptatum eaque saepe at quas, nulla voluptatem earum illum voluptatibus excepturi, vero accusamus. Magnam dolore, ex inventore officiis, nemo soluta doloremque asperiores nesciunt praesentium nobis nisi quam dicta blanditiis necessitatibus repudiandae modi laudantium, aut quas corporis repellat ratione perferendis? Quasi molestias rerum eligendi rem, deserunt, dignissimos perspiciatis aut laborum dolore maiores id corrupti quia doloremque maxime! Et, quis repellat?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque numquam nam expedita excepturi? Earum sunt impedit labore expedita esse dolorem perferendis nobis, doloribus optio dolores odit sed autem culpa nisi assumenda corrupti officia debitis aperiam reprehenderit ipsa corporis. Inventore, tenetur minus voluptatum eaque saepe at quas, nulla voluptatem earum illum voluptatibus excepturi, vero accusamus. Magnam dolore, ex inventore officiis, nemo soluta doloremque asperiores nesciunt praesentium nobis nisi quam dicta blanditiis necessitatibus repudiandae modi laudantium, aut quas corporis repellat ratione perferendis? Quasi molestias rerum eligendi rem, deserunt, dignissimos perspiciatis aut laborum dolore maiores id corrupti quia doloremque maxime! Et, quis repellat?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque numquam nam expedita excepturi? Earum sunt impedit labore expedita esse dolorem perferendis nobis, doloribus optio dolores odit sed autem culpa nisi assumenda corrupti officia debitis aperiam reprehenderit ipsa corporis. Inventore, tenetur minus voluptatum eaque saepe at quas, nulla voluptatem earum illum voluptatibus excepturi, vero accusamus. Magnam dolore, ex inventore officiis, nemo soluta doloremque asperiores nesciunt praesentium nobis nisi quam dicta blanditiis necessitatibus repudiandae modi laudantium, aut quas corporis repellat ratione perferendis? Quasi molestias rerum eligendi rem, deserunt, dignissimos perspiciatis aut laborum dolore maiores id corrupti quia doloremque maxime! Et, quis repellat?</p>
            </div>
        </main>
    )
}

export default Main